### ISSUE TITLE
[Breaking change] Need to remove hijiki

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#20]
It has been found by the [Canadian](http://www.inspection.gc.ca/food/information-for-consumers/fact-sheets-and-infographics/products-and-risks/chemical-hazards/inorganic-arsenic/eng/1332268146718/1332268231124), [US](https://web.archive.org/web/20140328011453/http://fsrio.nal.usda.gov/nal_web/fsrio/printresults.php?ID=4968), and [UK](https://web.archive.org/web/20130719114816/http://www.food.gov.uk/science/research/surveillance/fsis2004branch/fsis6104) governments that hijiki seaweed "contains a significant level of inorganic arsenic".
Furthermore, the US government states that "consumption of hijiki seaweed would *significantly increase daily dietary exposure to inorganic arsenic*. Consumers are therefore advised not to eat hijiki seaweed." (emphasis mine)

I suggest that hijiki be removed from [Grimgrains](https://grimgrains.com/#dried+hijiki) - this would mean a recipe would have to be modified, but I believe that that is OK given the dangers.

**Comment by microlith57** [comment]
On second thoughts, a large bold warning should do.

**Comment by neauoire** [comment]
I agree :) Or, `alert()` lol

**Comment by rekkabell** [comment]
I was aware of this, but did not think it harmful if consumed in small quantities (not daily, under 4.7g). Though since my recipes are mostly used by ppl outside of Japan (only country with no warning in place), it may be preferable to remove it for now, until I can make it again. I'll have to wait a while because I dont have access to the same ingredients here in Japan (tempeh for example). 
Thank you for your suggestions.
